# Site Settings
name: Devcast.ma
title: Devcast.ma | Podcast marocain
description: Le Podcast des Dev marocains animé par les Dev marocains 🤓
tags:
  - podcast
  - maroc
  - Developpeur
  - carrière
  - devcast.ma
  - devcast
email: zinoun.badr@gmail.com
disqus_username: badrzinoun
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml

#new etter 
    mailchimp-list : https://evidence-platform.us8.list-manage.com/subscribe/post?u=e8ecd68b6551ca6c9695798bf&amp;id=b27f588894

# Social Media Settings
# Remove the item if you don't need it
#github_username: github_username
facebook_username: devcast.ma
twitter_username: devcast_ma
instagram_username: devcast.ma
#linkedin_username: linkedin_username
#medium_username: medium_username


# Posts Settings
show_time_bar: false
show_modal_on_exit: true
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Translation Settings
translations:
  text:
    new_post: "Nouveau Podcast"
    see_also: "Ecouter aussi"
    search: "Recherche"
    author: "Auteur"
    share: "Parager"
    comments: "Commentaires"
  button:
    read_now: "Ecouter maintenant"
    share_on_twitter: "Partager sur Twitter"
    share_on_facebook: "Partager sur Facebook"
  pagination:
    page: "Page"
    of: "de"
    next_page: "Page suivante"
    next_post: "Page précédente"
  recommendation:
    text: "Pourquoi ne pas écouter quelque chose d'autre ?"
    back_btn: "Retour au début de la page"
  error_404:
    title: "Page non trouvée :("
    message: "Je suis désolé. Nous n'avons pas pu trouver la page que vous cherchez."
    image_alt: "404 - Page not found"
  contact:
    title: "Contacter nous"
    subject: "Nouveau contact!"
    submit_btn: "Envoyer"
    placeholders:
      name: "Votre nom"
      email: "Votre adresse électronique"
      message: "Votre message"
    errors:
      locale: "fr"
      empty_name: "Le nom est obligatoire"
      empty_email: "L'adresse électronique est obligatoire"
      invalid_email: "L'adresse électronique n'est pas valide"
      empty_message: "Le message est obligatoire"
    after_send:
      title: "Message envoyé !"
      message: "Je vous remercie de nous avoir contacté.Nous revenons vers vous dans les plus brefs délais."

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: true

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v1.1.0
